package com.devmod.shared;

import javax.annotation.Nonnull;

import net.minecraft.ChatFormatting;

import com.devmod.client.ui.editor.core.DesignTokens;

/**
 * Shared color tokens for common (client/server-safe) usage.
 * Values are sourced from DesignTokens; do not edit this file directly.
 */
public final class SharedColorTokens {

    private SharedColorTokens() {}

    public static final class Palette {
        public static final int BACKGROUND = DesignTokens.Palette.BACKGROUND;
        public static final int SURFACE = DesignTokens.Palette.SURFACE;
        public static final int SURFACE_ALT = DesignTokens.Palette.SURFACE_ALT;
        public static final int PANEL = DesignTokens.Palette.PANEL;
        public static final int OUTLINE = DesignTokens.Palette.OUTLINE;
        public static final int SHADOW = DesignTokens.Palette.SHADOW;
        public static final int TEXT_PRIMARY = DesignTokens.Palette.TEXT_PRIMARY;
        public static final int TEXT_SECONDARY = DesignTokens.Palette.TEXT_SECONDARY;
        public static final int ACCENT_TEAL = DesignTokens.Palette.ACCENT_TEAL;
        public static final int ACCENT_AMBER = DesignTokens.Palette.ACCENT_AMBER;
        public static final int ACCENT_BLUE = DesignTokens.Palette.ACCENT_BLUE;
        public static final int SUCCESS = DesignTokens.Palette.SUCCESS;
        public static final int WARNING = DesignTokens.Palette.WARNING;
        public static final int ERROR = DesignTokens.Palette.ERROR;

        private Palette() {}
    }

    public static class Mask {
        public static final int RGB = DesignTokens.Mask.RGB;
        public static final int ALPHA = DesignTokens.Mask.ALPHA;
        public static final int NONE = DesignTokens.Mask.NONE;

        protected Mask() {}
    }

    public static class Basic {
        public static final int RED = DesignTokens.Basic.RED;
        public static final int YELLOW = DesignTokens.Basic.YELLOW;
        public static final int GREEN = DesignTokens.Basic.GREEN;
        public static final int CYAN = DesignTokens.Basic.CYAN;
        public static final int BLUE = DesignTokens.Basic.BLUE;

        protected Basic() {}
    }

    public static class Chat {
        public static final @Nonnull ChatFormatting BLACK = DesignTokens.Chat.BLACK;
        public static final @Nonnull ChatFormatting DARK_BLUE = DesignTokens.Chat.DARK_BLUE;
        public static final @Nonnull ChatFormatting DARK_GREEN = DesignTokens.Chat.DARK_GREEN;
        public static final @Nonnull ChatFormatting DARK_AQUA = DesignTokens.Chat.DARK_AQUA;
        public static final @Nonnull ChatFormatting DARK_RED = DesignTokens.Chat.DARK_RED;
        public static final @Nonnull ChatFormatting DARK_PURPLE = DesignTokens.Chat.DARK_PURPLE;
        public static final @Nonnull ChatFormatting GOLD = DesignTokens.Chat.GOLD;
        public static final @Nonnull ChatFormatting GRAY = DesignTokens.Chat.GRAY;
        public static final @Nonnull ChatFormatting DARK_GRAY = DesignTokens.Chat.DARK_GRAY;
        public static final @Nonnull ChatFormatting BLUE = DesignTokens.Chat.BLUE;
        public static final @Nonnull ChatFormatting GREEN = DesignTokens.Chat.GREEN;
        public static final @Nonnull ChatFormatting AQUA = DesignTokens.Chat.AQUA;
        public static final @Nonnull ChatFormatting RED = DesignTokens.Chat.RED;
        public static final @Nonnull ChatFormatting LIGHT_PURPLE = DesignTokens.Chat.LIGHT_PURPLE;
        public static final @Nonnull ChatFormatting YELLOW = DesignTokens.Chat.YELLOW;
        public static final @Nonnull ChatFormatting WHITE = DesignTokens.Chat.WHITE;

        protected Chat() {}
    }

    public static class Message {
        public static final int RGB_SUCCESS = DesignTokens.Message.RGB_SUCCESS;
        public static final int RGB_ERROR = DesignTokens.Message.RGB_ERROR;
        public static final int RGB_MUTED = DesignTokens.Message.RGB_MUTED;

        protected Message() {}
    }

    public static class FollowRange {
        public static final int RED = DesignTokens.FollowRange.RED;
        public static final int YELLOW = DesignTokens.FollowRange.YELLOW;
        public static final int GREEN = DesignTokens.FollowRange.GREEN;
        public static final int CYAN = DesignTokens.FollowRange.CYAN;
        public static final int BLUE = DesignTokens.FollowRange.BLUE;

        protected FollowRange() {}
    }

    public static class Alert {
        public static final int ERROR = DesignTokens.Alert.ERROR;
        public static final int WARN = DesignTokens.Alert.WARN;
        public static final int INFO = DesignTokens.Alert.INFO;

        protected Alert() {}
    }

    public static class JourneyMap {
        public static final int SPAWN = DesignTokens.JourneyMap.SPAWN;
        public static final int OBJECTIVE = DesignTokens.JourneyMap.OBJECTIVE;
        public static final int EXIT = DesignTokens.JourneyMap.EXIT;

        protected JourneyMap() {}
    }

    public static class Heatmap {
        public static final int DEATH = DesignTokens.Heatmap.DEATH;
        public static final int MOVEMENT = DesignTokens.Heatmap.MOVEMENT;
        public static final int CAMPING = DesignTokens.Heatmap.CAMPING;
        public static final int STUCK = DesignTokens.Heatmap.STUCK;
        public static final int AGGRO_DROP = DesignTokens.Heatmap.AGGRO_DROP;
        public static final int KITING = DesignTokens.Heatmap.KITING;
        public static final int LIGHT_SPAWNABLE = DesignTokens.Heatmap.LIGHT_SPAWNABLE;
        public static final int LIGHT_DARK = DesignTokens.Heatmap.LIGHT_DARK;

        protected Heatmap() {}
    }

    public static class TelemetryExport {
        public static final int BG = DesignTokens.TelemetryExport.BG;
        public static final int TITLE = DesignTokens.TelemetryExport.TITLE;
        public static final int SUBTITLE = DesignTokens.TelemetryExport.SUBTITLE;
        public static final int GRID = DesignTokens.TelemetryExport.GRID;
        public static final int BORDER = DesignTokens.TelemetryExport.BORDER;
        public static final int LEGEND_TEXT = DesignTokens.TelemetryExport.LEGEND_TEXT;
        public static final int CELL_ALPHA = DesignTokens.TelemetryExport.CELL_ALPHA;

        public static final int GRADIENT_0 = DesignTokens.TelemetryExport.GRADIENT_0;
        public static final int GRADIENT_1 = DesignTokens.TelemetryExport.GRADIENT_1;
        public static final int GRADIENT_2 = DesignTokens.TelemetryExport.GRADIENT_2;
        public static final int GRADIENT_3 = DesignTokens.TelemetryExport.GRADIENT_3;
        public static final int GRADIENT_4 = DesignTokens.TelemetryExport.GRADIENT_4;
        public static final int GRADIENT_5 = DesignTokens.TelemetryExport.GRADIENT_5;
        public static final int GRADIENT_6 = DesignTokens.TelemetryExport.GRADIENT_6;
        public static final int GRADIENT_7 = DesignTokens.TelemetryExport.GRADIENT_7;
        public static final int GRADIENT_8 = DesignTokens.TelemetryExport.GRADIENT_8;
        public static final int GRADIENT_9 = DesignTokens.TelemetryExport.GRADIENT_9;

        protected TelemetryExport() {}
    }

    public static class AttributeLog {
        public static final int GREEN = DesignTokens.AttributeLog.GREEN;
        public static final int RED = DesignTokens.AttributeLog.RED;
        public static final int YELLOW = DesignTokens.AttributeLog.YELLOW;
        public static final int LIGHT_RED = DesignTokens.AttributeLog.LIGHT_RED;
        public static final int DARK_RED = DesignTokens.AttributeLog.DARK_RED;
        public static final int CRITICAL_RED = DesignTokens.AttributeLog.CRITICAL_RED;
        public static final int ORANGE = DesignTokens.AttributeLog.ORANGE;
        public static final int LIGHT_GREEN = DesignTokens.AttributeLog.LIGHT_GREEN;
        public static final int GRAY = DesignTokens.AttributeLog.GRAY;
        public static final int MAGENTA = DesignTokens.AttributeLog.MAGENTA;

        protected AttributeLog() {}
    }

    public static class BodyPart {
        public static final int HEAD = DesignTokens.BodyPart.HEAD;
        public static final int BODY = DesignTokens.BodyPart.BODY;
        public static final int ARMS = DesignTokens.BodyPart.ARMS;
        public static final int LEGS = DesignTokens.BodyPart.LEGS;

        protected BodyPart() {}
    }

    public static class Shield {
        public static final int DEFAULT = DesignTokens.Shield.DEFAULT;

        protected Shield() {}
    }

    public static class Combat {
        public static final class Text {
            public static final int PRIMARY = DesignTokens.Combat.Text.PRIMARY;
            public static final int MUTED = DesignTokens.Combat.Text.MUTED;
            public static final int WARNING = DesignTokens.Combat.Text.WARNING;

            private Text() {}
        }

        public static final class BodyPart {
            public static final int DEFAULT = DesignTokens.Combat.BodyPart.DEFAULT;
            public static final int HEAD = DesignTokens.Combat.BodyPart.HEAD;
            public static final int BODY = DesignTokens.Combat.BodyPart.BODY;
            public static final int ARMS = DesignTokens.Combat.BodyPart.ARMS;
            public static final int LEGS = DesignTokens.Combat.BodyPart.LEGS;

            private BodyPart() {}
        }

        public static final class ImprintStage {
            public static final int OWNER = DesignTokens.Combat.ImprintStage.OWNER;
            public static final int ENHANCED = DesignTokens.Combat.ImprintStage.ENHANCED;
            public static final int LEGENDARY = DesignTokens.Combat.ImprintStage.LEGENDARY;
            public static final int ASCENDED = DesignTokens.Combat.ImprintStage.ASCENDED;

            private ImprintStage() {}
        }

        public static final class WeaponTrait {
            public static final int EXECUTIONER = DesignTokens.Combat.WeaponTrait.EXECUTIONER;
            public static final int TYRANT_SLAYER = DesignTokens.Combat.WeaponTrait.TYRANT_SLAYER;
            public static final int STYLISH = DesignTokens.Combat.WeaponTrait.STYLISH;
            public static final int BLOODTHIRSTY = DesignTokens.Combat.WeaponTrait.BLOODTHIRSTY;
            public static final int HARMONIC = DesignTokens.Combat.WeaponTrait.HARMONIC;
            public static final int PRECISION = DesignTokens.Combat.WeaponTrait.PRECISION;
            public static final int RELENTLESS = DesignTokens.Combat.WeaponTrait.RELENTLESS;
            public static final int GUARDIAN = DesignTokens.Combat.WeaponTrait.GUARDIAN;
            public static final int DEVASTATING = DesignTokens.Combat.WeaponTrait.DEVASTATING;
            public static final int FINISHER = DesignTokens.Combat.WeaponTrait.FINISHER;
            public static final int CLEAVING = DesignTokens.Combat.WeaponTrait.CLEAVING;
            public static final int RETALIATING = DesignTokens.Combat.WeaponTrait.RETALIATING;

            private WeaponTrait() {}
        }

        protected Combat() {}
    }

    public static class Testing {
        public static final int SEPARATOR = DesignTokens.Testing.SEPARATOR;
        public static final int THUMB_NORMAL = DesignTokens.Testing.THUMB_NORMAL;
        public static final int THUMB_HOVER = DesignTokens.Testing.THUMB_HOVER;
        public static final int TRACK = DesignTokens.Testing.TRACK;
        public static final int HEADER_ACCENT = DesignTokens.Testing.HEADER_ACCENT;
        public static final int SUCCESS = DesignTokens.Testing.SUCCESS;
        public static final int ERROR = DesignTokens.Testing.ERROR;
        public static final int CYAN = DesignTokens.Testing.CYAN;
        public static final int TELEMETRY_ACCENT = DesignTokens.Testing.TELEMETRY_ACCENT;
        public static final int WARNING = DesignTokens.Testing.WARNING;
        public static final int ALERT = DesignTokens.Testing.ALERT;

        public static final class Status {
            public static final int PENDING = DesignTokens.Testing.Status.PENDING;
            public static final int IN_PROGRESS = DesignTokens.Testing.Status.IN_PROGRESS;
            public static final int PASSED = DesignTokens.Testing.Status.PASSED;
            public static final int FAILED = DesignTokens.Testing.Status.FAILED;
            public static final int SKIPPED = DesignTokens.Testing.Status.SKIPPED;

            private Status() {}
        }

        public static final class Priority {
            public static final int CRITICAL = DesignTokens.Testing.Priority.CRITICAL;
            public static final int HIGH = DesignTokens.Testing.Priority.HIGH;
            public static final int MEDIUM = DesignTokens.Testing.Priority.MEDIUM;
            public static final int LOW = DesignTokens.Testing.Priority.LOW;

            private Priority() {}
        }

        public static final class Level {
            public static final int LEVEL_1 = DesignTokens.Testing.Level.LEVEL_1;
            public static final int LEVEL_2 = DesignTokens.Testing.Level.LEVEL_2;
            public static final int LEVEL_3 = DesignTokens.Testing.Level.LEVEL_3;
            public static final int LEVEL_4 = DesignTokens.Testing.Level.LEVEL_4;
            public static final int LEVEL_5 = DesignTokens.Testing.Level.LEVEL_5;
            public static final int LEVEL_6 = DesignTokens.Testing.Level.LEVEL_6;
            public static final int LEVEL_7 = DesignTokens.Testing.Level.LEVEL_7;

            private Level() {}

            public static int forLevel(int level) {
                return DesignTokens.Testing.Level.forLevel(level);
            }
        }

        public static final class AchievementCategory {
            public static final int COMBAT = DesignTokens.Testing.AchievementCategory.COMBAT;
            public static final int PRECISION = DesignTokens.Testing.AchievementCategory.PRECISION;
            public static final int RANGED = DesignTokens.Testing.AchievementCategory.RANGED;
            public static final int SURVIVAL = DesignTokens.Testing.AchievementCategory.SURVIVAL;
            public static final int EXPLOSION = DesignTokens.Testing.AchievementCategory.EXPLOSION;
            public static final int ALCHEMY = DesignTokens.Testing.AchievementCategory.ALCHEMY;
            public static final int EXPLORER = DesignTokens.Testing.AchievementCategory.EXPLORER;
            public static final int DEDICATION = DesignTokens.Testing.AchievementCategory.DEDICATION;
            public static final int TESTING = DesignTokens.Testing.AchievementCategory.TESTING;
            public static final int SPECIAL = DesignTokens.Testing.AchievementCategory.SPECIAL;

            private AchievementCategory() {}
        }

        public static final class Badge {
            public static final int BRONZE_TESTER = DesignTokens.Testing.Badge.BRONZE_TESTER;
            public static final int SILVER_TESTER = DesignTokens.Testing.Badge.SILVER_TESTER;
            public static final int GOLD_TESTER = DesignTokens.Testing.Badge.GOLD_TESTER;
            public static final int DIAMOND_TESTER = DesignTokens.Testing.Badge.DIAMOND_TESTER;
            public static final int COMBAT_SPECIALIST = DesignTokens.Testing.Badge.COMBAT_SPECIALIST;
            public static final int PRECISION_EXPERT = DesignTokens.Testing.Badge.PRECISION_EXPERT;
            public static final int COMPLETIONIST = DesignTokens.Testing.Badge.COMPLETIONIST;

            private Badge() {}
        }

        protected Testing() {}
    }

    public static class Endurance {
        public static final class Text {
            public static final int WHITE = DesignTokens.Endurance.Text.WHITE;
            public static final int MUTED = DesignTokens.Endurance.Text.MUTED;

            private Text() {}
        }

        public static final class Currency {
            public static final int TOKENS = DesignTokens.Endurance.Currency.TOKENS;
            public static final int COINS = DesignTokens.Endurance.Currency.COINS;
            public static final int PRESTIGE = DesignTokens.Endurance.Currency.PRESTIGE;
            public static final int GEMS = DesignTokens.Endurance.Currency.GEMS;
            public static final int BLOOD_GEMS = DesignTokens.Endurance.Currency.BLOOD_GEMS;

            private Currency() {}
        }

        public static final class LootTier {
            public static final int COMMON = DesignTokens.Endurance.LootTier.COMMON;
            public static final int UNCOMMON = DesignTokens.Endurance.LootTier.UNCOMMON;
            public static final int RARE = DesignTokens.Endurance.LootTier.RARE;
            public static final int EPIC = DesignTokens.Endurance.LootTier.EPIC;
            public static final int LEGENDARY = DesignTokens.Endurance.LootTier.LEGENDARY;
            public static final int MYTHIC = DesignTokens.Endurance.LootTier.MYTHIC;

            private LootTier() {}
        }

        public static final class RewardCategory {
            public static final int STATS = DesignTokens.Endurance.RewardCategory.STATS;
            public static final int PERKS = DesignTokens.Endurance.RewardCategory.PERKS;
            public static final int UTILITY = DesignTokens.Endurance.RewardCategory.UTILITY;
            public static final int COSMETICS = DesignTokens.Endurance.RewardCategory.COSMETICS;

            private RewardCategory() {}
        }

        public static final class StyleRank {
            public static final int D = DesignTokens.Endurance.StyleRank.D;
            public static final int C = DesignTokens.Endurance.StyleRank.C;
            public static final int B = DesignTokens.Endurance.StyleRank.B;
            public static final int A = DesignTokens.Endurance.StyleRank.A;
            public static final int S = DesignTokens.Endurance.StyleRank.S;
            public static final int SS = DesignTokens.Endurance.StyleRank.SS;
            public static final int SSS = DesignTokens.Endurance.StyleRank.SSS;

            private StyleRank() {}
        }

        public static final class Momentum {
            public static final int STAGNANT = DesignTokens.Endurance.Momentum.STAGNANT;
            public static final int BUILDING = DesignTokens.Endurance.Momentum.BUILDING;
            public static final int HEATED = DesignTokens.Endurance.Momentum.HEATED;
            public static final int OVERDRIVE = DesignTokens.Endurance.Momentum.OVERDRIVE;

            private Momentum() {}
        }

        public static final class Flow {
            public static final int STALE = DesignTokens.Endurance.Flow.STALE;
            public static final int NEUTRAL = DesignTokens.Endurance.Flow.NEUTRAL;
            public static final int FRESH = DesignTokens.Endurance.Flow.FRESH;
            public static final int VIRTUOSO = DesignTokens.Endurance.Flow.VIRTUOSO;

            private Flow() {}
        }

        public static final class Tension {
            public static final int CALM = DesignTokens.Endurance.Tension.CALM;
            public static final int BUILDING = DesignTokens.Endurance.Tension.BUILDING;
            public static final int MODERATE = DesignTokens.Endurance.Tension.MODERATE;
            public static final int HIGH = DesignTokens.Endurance.Tension.HIGH;
            public static final int CRITICAL = DesignTokens.Endurance.Tension.CRITICAL;
            public static final int DEFAULT = DesignTokens.Endurance.Tension.DEFAULT;

            private Tension() {}
        }

        public static final class Tide {
            public static final int CALM = DesignTokens.Endurance.Tide.CALM;
            public static final int RISING = DesignTokens.Endurance.Tide.RISING;
            public static final int HIGH = DesignTokens.Endurance.Tide.HIGH;
            public static final int STORM = DesignTokens.Endurance.Tide.STORM;
            public static final int APOCALYPSE = DesignTokens.Endurance.Tide.APOCALYPSE;

            private Tide() {}
        }

        public static final class Boss {
            public static final int BERSERKER = DesignTokens.Endurance.Boss.BERSERKER;
            public static final int SUMMONER = DesignTokens.Endurance.Boss.SUMMONER;
            public static final int JUGGERNAUT = DesignTokens.Endurance.Boss.JUGGERNAUT;
            public static final int ASSASSIN = DesignTokens.Endurance.Boss.ASSASSIN;
            public static final int ELEMENTAL = DesignTokens.Endurance.Boss.ELEMENTAL;

            private Boss() {}
        }

        public static final class Contract {
            public static final int MINOR = DesignTokens.Endurance.Contract.MINOR;
            public static final int STANDARD = DesignTokens.Endurance.Contract.STANDARD;
            public static final int MAJOR = DesignTokens.Endurance.Contract.MAJOR;
            public static final int BLOOD = DesignTokens.Endurance.Contract.BLOOD;

            private Contract() {}
        }

        public static final class Kit {
            public static final int STARTER = DesignTokens.Endurance.Kit.STARTER;
            public static final int WARRIOR = DesignTokens.Endurance.Kit.WARRIOR;
            public static final int RANGER = DesignTokens.Endurance.Kit.RANGER;
            public static final int TANK = DesignTokens.Endurance.Kit.TANK;
            public static final int MAGE = DesignTokens.Endurance.Kit.MAGE;
            public static final int BERSERKER = DesignTokens.Endurance.Kit.BERSERKER;
            public static final int CUSTOM = DesignTokens.Endurance.Kit.CUSTOM;

            private Kit() {}
        }

        public static final class Prestige {
            public static final int PERK_SLOT = DesignTokens.Endurance.Prestige.PERK_SLOT;
            public static final int MUTATOR_UNLOCK = DesignTokens.Endurance.Prestige.MUTATOR_UNLOCK;
            public static final int ARENA_UNLOCK = DesignTokens.Endurance.Prestige.ARENA_UNLOCK;
            public static final int COSMETIC_TITLE = DesignTokens.Endurance.Prestige.COSMETIC_TITLE;
            public static final int STARTING_BONUS = DesignTokens.Endurance.Prestige.STARTING_BONUS;
            public static final int TOKEN_MULTIPLIER = DesignTokens.Endurance.Prestige.TOKEN_MULTIPLIER;
            public static final int EXCLUSIVE_PERK = DesignTokens.Endurance.Prestige.EXCLUSIVE_PERK;

            private Prestige() {}
        }

        public static final class PerkRarity {
            public static final int COMMON = DesignTokens.Endurance.PerkRarity.COMMON;
            public static final int UNCOMMON = DesignTokens.Endurance.PerkRarity.UNCOMMON;
            public static final int RARE = DesignTokens.Endurance.PerkRarity.RARE;
            public static final int EPIC = DesignTokens.Endurance.PerkRarity.EPIC;
            public static final int LEGENDARY = DesignTokens.Endurance.PerkRarity.LEGENDARY;

            private PerkRarity() {}
        }

        public static final class PerkCategory {
            public static final int OFFENSE = DesignTokens.Endurance.PerkCategory.OFFENSE;
            public static final int DEFENSE = DesignTokens.Endurance.PerkCategory.DEFENSE;
            public static final int UTILITY = DesignTokens.Endurance.PerkCategory.UTILITY;
            public static final int VAMPIRIC = DesignTokens.Endurance.PerkCategory.VAMPIRIC;
            public static final int ELEMENTAL = DesignTokens.Endurance.PerkCategory.ELEMENTAL;
            public static final int COMBO = DesignTokens.Endurance.PerkCategory.COMBO;
            public static final int CURSE = DesignTokens.Endurance.PerkCategory.CURSE;

            private PerkCategory() {}
        }

        public static final class Mutator {
            public static final int POSITIVE = DesignTokens.Endurance.Mutator.POSITIVE;
            public static final int NEGATIVE = DesignTokens.Endurance.Mutator.NEGATIVE;
            public static final int NEUTRAL = DesignTokens.Endurance.Mutator.NEUTRAL;
            public static final int CHAOTIC = DesignTokens.Endurance.Mutator.CHAOTIC;

            private Mutator() {}
        }

        public static final class Synergy {
            public static final int MINOR = DesignTokens.Endurance.Synergy.MINOR;
            public static final int MODERATE = DesignTokens.Endurance.Synergy.MODERATE;
            public static final int STRONG = DesignTokens.Endurance.Synergy.STRONG;
            public static final int LEGENDARY = DesignTokens.Endurance.Synergy.LEGENDARY;

            private Synergy() {}
        }

        public static final class ResonanceChain {
            public static final int DUO = DesignTokens.Endurance.ResonanceChain.DUO;
            public static final int TRINITY = DesignTokens.Endurance.ResonanceChain.TRINITY;
            public static final int APOCALYPSE = DesignTokens.Endurance.ResonanceChain.APOCALYPSE;
            public static final int DEFAULT = DesignTokens.Endurance.ResonanceChain.DEFAULT;

            private ResonanceChain() {}
        }

        public static final class Hazard {
            public static final int FIRE = DesignTokens.Endurance.Hazard.FIRE;
            public static final int BLEED = DesignTokens.Endurance.Hazard.BLEED;
            public static final int VOID = DesignTokens.Endurance.Hazard.VOID;
            public static final int ARC = DesignTokens.Endurance.Hazard.ARC;
            public static final int PSI = DesignTokens.Endurance.Hazard.PSI;

            private Hazard() {}
        }

        public static final class Nemesis {
            public static final int PROJECTILE_DEFLECTION = DesignTokens.Endurance.Nemesis.PROJECTILE_DEFLECTION;
            public static final int SWEEPING_BLADE = DesignTokens.Endurance.Nemesis.SWEEPING_BLADE;
            public static final int EARLY_PHASE_ACTIVATION = DesignTokens.Endurance.Nemesis.EARLY_PHASE_ACTIVATION;
            public static final int DAMAGE_RESISTANCE = DesignTokens.Endurance.Nemesis.DAMAGE_RESISTANCE;
            public static final int PROTECTIVE_HELMET = DesignTokens.Endurance.Nemesis.PROTECTIVE_HELMET;
            public static final int IMPROVED_REFLEXES = DesignTokens.Endurance.Nemesis.IMPROVED_REFLEXES;
            public static final int ENRAGED = DesignTokens.Endurance.Nemesis.ENRAGED;
            public static final int VETERAN = DesignTokens.Endurance.Nemesis.VETERAN;
            public static final int EVASION = DesignTokens.Endurance.Nemesis.EVASION;
            public static final int REGENERATION = DesignTokens.Endurance.Nemesis.REGENERATION;
            public static final int SUMMONER = DesignTokens.Endurance.Nemesis.SUMMONER;

            private Nemesis() {}
        }

        public static final class Bargain {
            public static final int GLASS_CANNON = DesignTokens.Endurance.Bargain.GLASS_CANNON;
            public static final int SLUGGISH = DesignTokens.Endurance.Bargain.SLUGGISH;
            public static final int FUMBLING = DesignTokens.Endurance.Bargain.FUMBLING;
            public static final int HUNGER = DesignTokens.Endurance.Bargain.HUNGER;
            public static final int ECHO_DAMAGE = DesignTokens.Endurance.Bargain.ECHO_DAMAGE;
            public static final int BLOOD_TITHE = DesignTokens.Endurance.Bargain.BLOOD_TITHE;
            public static final int CROWD_PRESSURE = DesignTokens.Endurance.Bargain.CROWD_PRESSURE;
            public static final int FRAILTY = DesignTokens.Endurance.Bargain.FRAILTY;
            public static final int BURNING_SOUL = DesignTokens.Endurance.Bargain.BURNING_SOUL;
            public static final int COMBO_BREAKER = DesignTokens.Endurance.Bargain.COMBO_BREAKER;
            public static final int MOMENTUM_DRAIN = DesignTokens.Endurance.Bargain.MOMENTUM_DRAIN;
            public static final int ONE_SHOT = DesignTokens.Endurance.Bargain.ONE_SHOT;
            public static final int ELITE_HUNTER = DesignTokens.Endurance.Bargain.ELITE_HUNTER;
            public static final int NO_HEALING = DesignTokens.Endurance.Bargain.NO_HEALING;
            public static final int EXECUTIONER = DesignTokens.Endurance.Bargain.EXECUTIONER;

            private Bargain() {}
        }

        public static final class BargainTier {
            public static final int MINOR = DesignTokens.Endurance.BargainTier.MINOR;
            public static final int MAJOR = DesignTokens.Endurance.BargainTier.MAJOR;
            public static final int CURSED = DesignTokens.Endurance.BargainTier.CURSED;

            private BargainTier() {}
        }

        protected Endurance() {}
    }

    public static class Foundry {
        public static final class Quality {
            public static final int CRUDE = DesignTokens.Foundry.Quality.CRUDE;
            public static final int STANDARD = DesignTokens.Foundry.Quality.STANDARD;
            public static final int REFINED = DesignTokens.Foundry.Quality.REFINED;
            public static final int PRISTINE = DesignTokens.Foundry.Quality.PRISTINE;
            public static final int MASTERWORK = DesignTokens.Foundry.Quality.MASTERWORK;

            private Quality() {}
        }

        public static final class Fluids {
            public static final int MOLTEN_IRON = DesignTokens.Foundry.Fluids.MOLTEN_IRON;
            public static final int MOLTEN_GOLD = DesignTokens.Foundry.Fluids.MOLTEN_GOLD;
            public static final int MOLTEN_COPPER = DesignTokens.Foundry.Fluids.MOLTEN_COPPER;
            public static final int MOLTEN_TIN = DesignTokens.Foundry.Fluids.MOLTEN_TIN;
            public static final int MOLTEN_BRONZE = DesignTokens.Foundry.Fluids.MOLTEN_BRONZE;
            public static final int MOLTEN_STEEL = DesignTokens.Foundry.Fluids.MOLTEN_STEEL;
            public static final int MOLTEN_COBALT = DesignTokens.Foundry.Fluids.MOLTEN_COBALT;
            public static final int MOLTEN_MANYULLYN = DesignTokens.Foundry.Fluids.MOLTEN_MANYULLYN;
            public static final int MOLTEN_LEAD = DesignTokens.Foundry.Fluids.MOLTEN_LEAD;
            public static final int MOLTEN_SILVER = DesignTokens.Foundry.Fluids.MOLTEN_SILVER;
            public static final int MOLTEN_NICKEL = DesignTokens.Foundry.Fluids.MOLTEN_NICKEL;
            public static final int MOLTEN_ELECTRUM = DesignTokens.Foundry.Fluids.MOLTEN_ELECTRUM;
            public static final int MOLTEN_INVAR = DesignTokens.Foundry.Fluids.MOLTEN_INVAR;
            public static final int MOLTEN_ARDITE = DesignTokens.Foundry.Fluids.MOLTEN_ARDITE;
            public static final int MOLTEN_NETHERITE = DesignTokens.Foundry.Fluids.MOLTEN_NETHERITE;
            public static final int MOLTEN_VOID_METAL = DesignTokens.Foundry.Fluids.MOLTEN_VOID_METAL;

            private Fluids() {}
        }

        public static final class Risk {
            public static final int SAFE = DesignTokens.Foundry.Risk.SAFE;
            public static final int ELEVATED = DesignTokens.Foundry.Risk.ELEVATED;
            public static final int HIGH = DesignTokens.Foundry.Risk.HIGH;
            public static final int CRITICAL = DesignTokens.Foundry.Risk.CRITICAL;

            private Risk() {}
        }

        public static final class PatternTier {
            public static final int BASIC = DesignTokens.Foundry.PatternTier.BASIC;
            public static final int STANDARD = DesignTokens.Foundry.PatternTier.STANDARD;
            public static final int QUALITY = DesignTokens.Foundry.PatternTier.QUALITY;
            public static final int MASTER = DesignTokens.Foundry.PatternTier.MASTER;
            public static final int ANCIENT = DesignTokens.Foundry.PatternTier.ANCIENT;

            private PatternTier() {}
        }

        public static final class Pattern {
            public static final int SPECIALIZED = DesignTokens.Foundry.Pattern.SPECIALIZED;
            public static final int DURABILITY_HIGH = DesignTokens.Foundry.Pattern.DURABILITY_HIGH;
            public static final int DURABILITY_MEDIUM = DesignTokens.Foundry.Pattern.DURABILITY_MEDIUM;
            public static final int DURABILITY_LOW = DesignTokens.Foundry.Pattern.DURABILITY_LOW;

            private Pattern() {}
        }

        public static final class Material {
            public static final int DEFAULT_COLOR = DesignTokens.Foundry.Material.DEFAULT_COLOR;

            private Material() {}
        }

        protected Foundry() {}
    }
}
