package com.devmod.arena.spawn;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class SpawnSlotTest {

    @Test
    void atCreatesPlayerSlot() {
        SpawnSlot slot = SpawnSlot.at(10.0, 64.0, 20.0);
        assertEquals(10.0, slot.x());
        assertEquals(64.0, slot.y());
        assertEquals(20.0, slot.z());
        assertEquals(0.0f, slot.yaw());
        assertEquals(0.0f, slot.pitch());
        assertEquals(SpawnSlot.SpawnSlotType.PLAYER, slot.type());
        assertEquals(0, slot.teamIndex());
    }

    @Test
    void forTeam() {
        SpawnSlot slot = SpawnSlot.forTeam(5.0, 10.0, 15.0, 2);
        assertEquals(SpawnSlot.SpawnSlotType.TEAM, slot.type());
        assertEquals(2, slot.teamIndex());
    }

    @Test
    void distanceTo() {
        SpawnSlot a = SpawnSlot.at(0, 0, 0);
        SpawnSlot b = SpawnSlot.at(3, 4, 0);
        assertEquals(5.0, a.distanceTo(b), 0.001);
    }

    @Test
    void distanceToSelf() {
        SpawnSlot slot = SpawnSlot.at(10, 20, 30);
        assertEquals(0.0, slot.distanceTo(slot));
    }

    @Test
    void horizontalDistanceTo() {
        SpawnSlot a = SpawnSlot.at(0, 0, 0);
        SpawnSlot b = SpawnSlot.at(3, 100, 4); // Y difference ignored
        assertEquals(5.0, a.horizontalDistanceTo(b), 0.001);
    }

    @Test
    void getPosition() {
        SpawnSlot slot = SpawnSlot.at(1.5, 2.5, 3.5);
        double[] pos = slot.getPosition();
        assertArrayEquals(new double[]{1.5, 2.5, 3.5}, pos);
    }

    @Test
    void getRotation() {
        SpawnSlot slot = new SpawnSlot(0, 0, 0, 90.0f, -45.0f, SpawnSlot.SpawnSlotType.PLAYER, 0);
        float[] rot = slot.getRotation();
        assertArrayEquals(new float[]{90.0f, -45.0f}, rot);
    }

    @Test
    void withPosition() {
        SpawnSlot original = SpawnSlot.at(0, 0, 0);
        SpawnSlot moved = original.withPosition(10, 20, 30);
        assertEquals(10.0, moved.x());
        assertEquals(20.0, moved.y());
        assertEquals(30.0, moved.z());
        assertEquals(original.id(), moved.id());
        assertEquals(original.type(), moved.type());
    }

    @Test
    void withRotation() {
        SpawnSlot original = SpawnSlot.at(0, 0, 0);
        SpawnSlot rotated = original.withRotation(90.0f, -30.0f);
        assertEquals(90.0f, rotated.yaw());
        assertEquals(-30.0f, rotated.pitch());
        assertEquals(original.id(), rotated.id());
    }

    @Test
    void withTeam() {
        SpawnSlot original = SpawnSlot.at(0, 0, 0);
        SpawnSlot teamSlot = original.withTeam(3);
        assertEquals(3, teamSlot.teamIndex());
        assertEquals(original.id(), teamSlot.id());
    }

    @Test
    void spawnSlotTypeValues() {
        assertEquals(5, SpawnSlot.SpawnSlotType.values().length);
        assertNotNull(SpawnSlot.SpawnSlotType.valueOf("PLAYER"));
        assertNotNull(SpawnSlot.SpawnSlotType.valueOf("TEAM"));
        assertNotNull(SpawnSlot.SpawnSlotType.valueOf("SPECTATOR"));
        assertNotNull(SpawnSlot.SpawnSlotType.valueOf("WAITING"));
        assertNotNull(SpawnSlot.SpawnSlotType.valueOf("VIP"));
    }

    @Test
    void autoGeneratedIdIsUnique() {
        SpawnSlot a = SpawnSlot.at(0, 0, 0);
        SpawnSlot b = SpawnSlot.at(0, 0, 0);
        assertNotEquals(a.id(), b.id());
    }
}
